ToDoList/Controllers/ToDoController.cs
using ToDoList.Models;
using ToDoList.Models.DTOs;
using ToDoList.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoList.Controllers
{
    public class ToDoController : Controller
    {
        private IToDoService toDoService;
        private UserManager<User> userManager;
        public ToDoController(IToDoService toDoService, UserManager<User> userManager)
        {
            this.toDoService = toDoService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            List<ToDoDTO> toDoes = toDoService.GetAll();

            return View(toDoes);
        }
        public async Task<IActionResult> UserToDoes()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            List<ToDoDTO> toDoes = toDoService.GetUserToDoes(user.Id);
            return View(toDoes);
        }

        public IActionResult ShowSearchForm()
        {
            return View();
        }

        public async Task<IActionResult> ShowSearchResultName(String SearchPhrase)
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            List<ToDoDTO> toDoes = toDoService.GetUserToDoesName(user.Id, SearchPhrase);
            return View(toDoes);
        }

        public async Task<IActionResult> ShowSearchResultDifficulty(String SearchPhrase)
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            List<ToDoDTO> toDoes = toDoService.GetUserToDoesDifficulty(user.Id, SearchPhrase);
            return View(toDoes);
        }

        public async Task<IActionResult> SortName()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
 
            return View(toDoService.GetToDoSortName(user.Id));
        }

        public async Task<IActionResult> SortNameDesc()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);

            return View(toDoService.GetToDoSortNameDesc(user.Id));
        }
        public async Task<IActionResult> SortDescribtion()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);

            return View(toDoService.GetToDoSortDescribtion(user.Id));
        }
        public async Task<IActionResult> SortDescribtionDesc()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            
            return View(toDoService.GetToDoSortDescribtionDesc(user.Id));
        }

        public async Task<IActionResult> SortDifficulty()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);

            return View(toDoService.GetToDoSortDifficulty(user.Id));
        }
        public async Task<IActionResult> SortDifficultyDesc()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);

            return View(toDoService.GetToDoSortDifficultyDesc(user.Id));
        }

        public async Task<IActionResult> SortStartDate()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);

            return View(toDoService.GetToDoSortStartDate(user.Id));
        }
        public async Task<IActionResult> SortStartDateDesc()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);

            return View(toDoService.GetToDoSortStartDateDesc(user.Id));
        }

        public async Task<IActionResult> SortEndDate()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);

            return View(toDoService.GetToDoSortEndDate(user.Id));
        }
        public async Task<IActionResult> SortEndDateDesc()
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);

            return View(toDoService.GetToDoSortEndDateDesc(user.Id));
        }

        public IActionResult Details(int id)
        {
            ToDoDTO toDo = toDoService.GetDtoById(id);
            return View(toDo);
        }
        public IActionResult Edit()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> EditAsync(int id)
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            ToDo toDo = toDoService.GetById(id);
            if (user is null)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            if (toDo.UserId != user.Id)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            return View(toDoService.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, ToDo toDo)
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            if (user is null)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            if (toDoService.GetById(id).UserId != user.Id)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            toDoService.Edit(toDo);
            return RedirectToAction(nameof(UserToDoes));
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(ToDo toDo)
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            if (user is null)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            if (!ModelState.IsValid)
            {
                return View();
            }
            toDoService.Create(toDo, user);
            return RedirectToAction(nameof(UserToDoes));
        }
        [HttpGet]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            ToDo toDo = toDoService.GetById(id);
            if (user is null)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            if (toDo.UserId != user.Id)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            return View(toDo);
        }
        public async Task<IActionResult> ConfirmDeleteAsync(int id)
        {
            User user = await userManager.GetUserAsync(User).ConfigureAwait(false);
            ToDo toDo = toDoService.GetById(id);
            if (user is null)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            if (toDo.UserId != user.Id)
            {
                return RedirectToAction(nameof(UserToDoes));
            }
            toDoService.Delete(id);
            return RedirectToAction(nameof(UserToDoes));
        }
        [HttpGet]
        public IActionResult ViewToDo(int id)
        {
            return View(toDoService.GetById(id));
        }
    }
}

ToDoList/Controllers/UserController.cs
using ToDoList.Models;
using ToDoList.Models.DTOs;
using ToDoList.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoList.Controllers
{
    public class UserController : Controller
    {
        private IUserService userService;
        private UserManager<User> userManager;

        public UserController(UserManager<User> userManager, IUserService userService)
        {
            this.userService = userService;
            this.userManager = userManager;
        }



        [HttpGet]
        public async Task<IActionResult> Details()
        {
            User user = await userManager.GetUserAsync(User);
            TempData["loggedId"] = user.Id;
            UserDTO userDTO = userService.GetById(user.Id);


            return View(userDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UserDTO userDTO)
        {

            User user = await userManager.GetUserAsync(User);
            _ = TempData["loggedId"];
            userService.Update(user.Id, userDTO);


            return RedirectToAction(nameof(Details));
        }

        [HttpGet]
        public async Task<IActionResult> Delete()
        {
            User user = await userManager.GetUserAsync(User);
            userService.Delete(user.Id);

            return RedirectToAction("Logout", "Account");
        }

    }
}

ToDoList/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using ToDoList.Data;
@inject SignInManager<User> signinManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.signinManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="UserToDoes">ToDo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Details">Profile(@User.Identity.Name)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Profile</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>